import '../styles/reset.css';
import '../styles/layout.css';
import '../styles/fonts.css';
import '../styles/colors.css';
import '../styles/globals.css';
import Flex from '@/components/generic/Flex';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {/* <Flex style={{ height: '64px', alignItems: 'center', padding: '40px' }}>
          StoryForks
        </Flex> */}
        <main>{children}</main>
        {/* <Flex
          style={{
            height: '200px',
            justifyContent: 'center',
            alignItems: 'center',
          }}
        >
          Footer
        </Flex> */}
      </body>
    </html>
  );
}
